# Secret para baixar imagens do github
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: aproove
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZVzVrY21Wd1pXNTBaV0ZrYnpwbmFIQmZORTgxVmtWWlIzZGhkbUo1VjJOcE1uQlhWV2MxV21ad1IyeEZibXR6TURkWWJEaEgiCgkJfQoJfSwKCSJhbGlhc2VzIjogewoJCSJidWlsZGVyIjogImJ1aWxkeCIKCX0KfQ==
type: kubernetes.io/dockerconfigjson