name: Compilar e Testar o Backend

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db-server:
        image: postgres:14
        env:
          POSTGRES_DB: dbname-ap-roove
          POSTGRES_USER: dbuser-ap-roove
          POSTGRES_PASSWORD: dbpasswd-ap-roove

    steps:
    - name: Checkout do projeto
      uses: actions/checkout@v3

    - name: Usar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: 'maven'

    - name: Compilar e Testar
      run: mvn -B clean package --file backend/pom.xml